# payload-guardian.sh — GENERIC procd runtime owner / guardian for a payload tenant (#156/#167/#274).
#
# Sourced by a per-tenant init stub (/etc/init.d/batman-payload-<tenant>, generated by
# restore_payload_guardians from /usr/share/batman/payload-guardian.init.in) that sets PAYLOAD_TENANT then
# `. /usr/lib/batman/payload-guardian.sh`.
#
# The guardian is the ONLY component that starts or restarts a tenant container: every container is created
# `--restart no`, so nothing comes up by itself after a power loss or an OTA, and the start is always the
# ordered, health-gated start mode (docs/design/274-payload-converge.md §12, v8.2). The supervised body is
# /usr/lib/batman/payload-guardian-run.sh (start-up converge, 5 s liveness poll + restarts, 30 s verdict).
#
# BOOT ORDERING: dockerd is START=99 and "batman-payload-*" sorts before "dockerd", so this starts first; the
# body waits up to 90 s for the docker API and procd respawns it otherwise.
#
# Stop = graceful and tiered (/usr/lib/batman/payload-stop.sh; K08batman-prestop-payload + this K09), never
# rm, so the next boot is a start, not a rebuild.
#
# shellcheck shell=sh

APPS_DIR="${APPS_DIR:-/opt/batdata/apps}"
_T="${PAYLOAD_TENANT:?payload-guardian.sh: PAYLOAD_TENANT not set by the init stub}"
_DIR="$APPS_DIR/$_T"

# shellcheck source=/dev/null
[ -r /usr/lib/batman/rundir.sh ] && . /usr/lib/batman/rundir.sh   # #280: root-only run dir (RUNDIR)
_R="${PAYLOAD_RUNDIR:-${RUNDIR:-/nonexistent/batman-rundir}}"

start_service() {
	[ -d "$_DIR" ] || { echo "batman-payload[$_T]: $_DIR missing (payload not installed)"; return 1; }
	# #280 fail closed: no private run dir = no trustworthy verdict/stop state -> do not start the tenant
	if [ -z "${PAYLOAD_RUNDIR:-}" ]; then
		type batman_rundir >/dev/null 2>&1 && batman_rundir || { echo "batman-payload[$_T]: run dir unusable (#280) — not starting"; return 1; }
	fi
	# #274 D7-4: a system shutdown is never undone by a late start (firstload's detached loader, an operator)
	[ -e "$_R/batman-shutdown" ] && { logger -t "batman-payload-$_T" "start refused: the node is shutting down"; return 1; }
	# a start ends any stop; .up removed so the body can tell a procd respawn (.up present) from this start
	rm -f "$_R/batman-payload-$_T.stopping" "$_R/batman-payload-$_T.stop0" "$_R/batman-payload-$_T.up"
	procd_open_instance
	procd_set_param command /bin/sh /usr/lib/batman/payload-guardian-run.sh "$_T"
	procd_set_param respawn 30 15 0    # threshold 30s, respawn every 15s, unlimited retries
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	# Graceful, tiered stop of the tenant; never rm, so the next start is a start, not a rebuild (#274).
	# At shutdown K08batman-prestop-payload has already stopped the client tiers; this (K09) stops the
	# stateful services and records the stop. An operator `stop` runs both halves here.
	[ -f /usr/lib/batman/payload-stop.sh ] || return 0
	# shellcheck source=/dev/null
	. /usr/lib/batman/payload-stop.sh
	pstop_final "$_T"
}
