#!/usr/bin/env python3
"""profile-to-fw4.py — derive the fw4 (nftables) rules for a payload from its descriptor (#68/#162).

App-agnostic companion to profile-to-flags.py. Reads deploy/<app>/profile.yaml `network:` block
(the operational SoT for networking) and writes deploy/<app>/<app>.fw4.uci — a shell script of
`uci`/`fw4` commands the busybox node runs as a uci-default (the node NEVER parses YAML; this runs
on the dev machine / in CI). Implements the on-node-VALIDATED design B (docs/design/ots-networking.md):

  docker iptables=0 + a per-app bridge + a per-app fw4 zone (input=DROP, intra-zone forward,
  no cross-zone forward = no mesh leak) + fw4-native DNAT publish + one narrow src_zone->dport allow.

The emitted script is idempotent (delete-then-set) and safe to re-run. It does NOT set
dockerd.globals.iptables (that is a one-time node prep, done by run.sh/README), only the firewall.

Usage:  profile-to-fw4.py <app>            # writes deploy/<app>/<app>.fw4.uci
        profile-to-fw4.py <app> --check    # print to stdout only (CI diff), write nothing
"""
import sys, pathlib
try:
    import yaml
except ImportError:
    sys.exit("PyYAML required (pip install pyyaml)")

REPO = pathlib.Path(__file__).resolve().parent.parent


def uci_from_network(app, net):
    zone = net.get("zone", f"{app}z")
    br = net.get("bridge", {})
    dev = br.get("name")
    if not dev:
        sys.exit(f"{app}: network.bridge.name required")
    iso = net.get("isolation", {})
    inp = iso.get("input", "DROP")
    # forward=intra-zone -> zone forward ACCEPT (intra-zone only; no forwarding entries = no cross-zone)
    fwd = "ACCEPT" if iso.get("forward") == "intra-zone" else "DROP"
    pub = net.get("publish", []) or []
    peers = net.get("peer_allow", []) or []

    # group DNAT publishes into allow rules by (src_zone,dest_ip,proto) — compute upfront so
    # the idempotent cleanup can enumerate every generated section (allow, allow1, allow2, ...).
    allow = {}  # (src_zone,dest_ip,proto) -> set(dports)
    for p in pub:
        dip = p["to"].rsplit(":", 1)[0]
        allow.setdefault((p["src_zone"], dip, p.get("proto", "tcp")), set()).add(str(p["to"].rsplit(":", 1)[1]))
    allow_names = [f"{app}_allow" if j == 0 else f"{app}_allow{j}" for j in range(len(allow))]

    L = []
    a = L.append
    a("#!/bin/sh")
    a(f"# GENERATED by scripts/profile-to-fw4.py from deploy/{app}/profile.yaml -- DO NOT EDIT BY HAND.")
    a("# fw4 rules for the payload's docker bridge (design B, docs/design/ots-networking.md).")
    a("# Idempotent; install as a uci-default or source from run.sh. Requires dockerd iptables=0.")
    a("set -e")
    # clean prior (idempotent) — every section this script may create
    names = [f"{app}_zone"] + allow_names + [f"{app}_dnat_{i}" for i in range(len(pub))] \
            + [f"{app}_peer_{i}" for i in range(len(peers))]
    a(f'for s in {" ".join(names)}; do uci -q delete firewall."$s" || true; done')
    # zone
    a(f"uci set firewall.{app}_zone=zone")
    a(f"uci set firewall.{app}_zone.name='{zone}'")
    a(f"uci set firewall.{app}_zone.device='{dev}'")
    a(f"uci set firewall.{app}_zone.input='{inp}'")
    a(f"uci set firewall.{app}_zone.output='ACCEPT'")
    a(f"uci set firewall.{app}_zone.forward='{fwd}'")
    a(f"uci set firewall.{app}_zone.masq='0'")
    # DNAT publish (allow grouping already computed above)
    for i, p in enumerate(pub):
        sz, hp, to, proto = p["src_zone"], p["host_port"], p["to"], p.get("proto", "tcp")
        dip, dport = to.rsplit(":", 1)
        a(f"uci set firewall.{app}_dnat_{i}=redirect")
        a(f"uci set firewall.{app}_dnat_{i}.name='{app}-pub-{hp}'")
        a(f"uci set firewall.{app}_dnat_{i}.src='{sz}'")
        a(f"uci set firewall.{app}_dnat_{i}.src_dport='{hp}'")
        a(f"uci set firewall.{app}_dnat_{i}.dest='{zone}'")
        a(f"uci set firewall.{app}_dnat_{i}.dest_ip='{dip}'")
        a(f"uci set firewall.{app}_dnat_{i}.dest_port='{dport}'")
        a(f"uci set firewall.{app}_dnat_{i}.proto='{proto}'")
        a(f"uci set firewall.{app}_dnat_{i}.target='DNAT'")
    # one allow rule per (src_zone,dest_ip,proto) — zone forward policy may be DROP for cross-zone
    for j, ((sz, dip, proto), ports) in enumerate(sorted(allow.items())):
        a(f"uci set firewall.{app}_allow=rule" if j == 0 else f"uci set firewall.{app}_allow{j}=rule")
        pfx = f"{app}_allow" if j == 0 else f"{app}_allow{j}"
        a(f"uci set firewall.{pfx}.name='{app}-pub-allow'")
        a(f"uci set firewall.{pfx}.src='{sz}'")
        a(f"uci set firewall.{pfx}.dest='{zone}'")
        a(f"uci set firewall.{pfx}.dest_ip='{dip}'")
        a(f"uci set firewall.{pfx}.proto='{proto}'")
        a(f"uci set firewall.{pfx}.dest_port='{' '.join(sorted(ports))}'")
        a(f"uci set firewall.{pfx}.target='ACCEPT'")
    # explicit app<->app allows (default none) — cross-zone exceptions
    for i, pa in enumerate(peers):
        a(f"uci set firewall.{app}_peer_{i}=rule")
        a(f"uci set firewall.{app}_peer_{i}.name='{app}-peer-{i}'")
        a(f"uci set firewall.{app}_peer_{i}.src='{pa['from_zone']}'")
        a(f"uci set firewall.{app}_peer_{i}.dest='{zone}'")
        a(f"uci set firewall.{app}_peer_{i}.proto='{pa.get('proto','tcp')}'")
        a(f"uci set firewall.{app}_peer_{i}.dest_port='{pa['dest_port']}'")
        a(f"uci set firewall.{app}_peer_{i}.target='ACCEPT'")
    a("uci commit firewall")
    a("fw4 reload >/dev/null 2>&1 || true")
    a(f'echo "fw4: {app} zone {zone} on {dev} applied"')
    return "\n".join(L) + "\n"


def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    app = sys.argv[1]
    check = "--check" in sys.argv[2:]
    prof = REPO / "deploy" / app / "profile.yaml"
    if not prof.exists():
        sys.exit(f"no profile: {prof}")
    doc = yaml.safe_load(prof.read_text(encoding="utf-8")) or {}
    net = doc.get("network")
    if not net:
        sys.exit(f"{app}: no top-level network: block (host-net apps emit no fw4 zone)")
    out = uci_from_network(app, net)
    if check:
        sys.stdout.write(out)
    else:
        dst = REPO / "deploy" / app / f"{app}.fw4.uci"
        with open(dst, "w", encoding="utf-8", newline="\n") as fh:   # LF only — the node runs this under sh
            fh.write(out)
        print(f"wrote {dst.relative_to(REPO)}")


if __name__ == "__main__":
    main()
