#!/usr/bin/env python3
"""profile-to-flags.py — derive docker hardening flags from a tenant security profile (#98/#153).

App-agnostic: reads deploy/<app>/profile.yaml `values` block (the machine-readable SoT) and writes
deploy/<app>/<app>.hardening.env, a flat KEY=VAL file the busybox node can `source` (no YAML on-node).
The node NEVER parses YAML; this runs on the dev machine / in CI. `values` describes what is actually
applied — only CONFINEMENT flags are emitted here; app-specifics (image, volumes, ports, --network,
env, cwd) stay in the app's run.sh.

Usage:  profile-to-flags.py <app>            # writes deploy/<app>/<app>.hardening.env
        profile-to-flags.py <app> --check    # print to stdout only (CI diff), write nothing

Emitted axes: user, no_new_privileges, caps(drop/add), rootfs(read_only+tmpfs), resources(cpus/pids/memory),
devices, seccomp(non-default only). Absent/false axes emit nothing (values==applied; staging is operational).
"""
import sys, os, pathlib
try:
    import yaml
except ImportError:
    sys.exit("PyYAML required (pip install pyyaml)")

REPO = pathlib.Path(__file__).resolve().parent.parent

def flags_from_values(v):
    f = []
    u = v.get("user", {})
    if u.get("run_as") is not None:
        uid = str(u["run_as"])
        f.append(f"--user {uid}:{u['run_as_gid']}" if u.get("run_as_gid") is not None else f"--user {uid}")
    if v.get("no_new_privileges"):
        f.append("--security-opt no-new-privileges")
    caps = v.get("caps", {})
    for d in caps.get("drop", []) or []:
        f.append(f"--cap-drop={d}")
    for a in caps.get("add", []) or []:
        f.append(f"--cap-add={a}")
    rootfs = v.get("rootfs", {})
    if rootfs.get("read_only"):
        f.append("--read-only")
    for t in rootfs.get("tmpfs", []) or []:
        f.append(f"--tmpfs {t}")
    res = v.get("resources", {})
    if res.get("cpus") is not None:
        f.append(f"--cpus {res['cpus']}")
    if res.get("pids") is not None:
        f.append(f"--pids-limit {res['pids']}")
    if res.get("memory") is not None:          # omitted until load-measured (B3/Stage 5)
        f.append(f"--memory {res['memory']}")
    for d in v.get("devices", []) or []:
        f.append(f"--device {d}")
    sec = v.get("seccomp", {})
    if sec.get("profile") and sec["profile"] != "default":
        f.append(f"--security-opt seccomp={sec['profile']}")
    return f

def main():
    if len(sys.argv) < 2:
        sys.exit(__doc__)
    app = sys.argv[1]
    rest = sys.argv[2:]
    check = "--check" in rest
    want = [a for a in rest if not a.startswith("--")]   # optional: limit --check to these env filenames
    prof = REPO / "deploy" / app / "profile.yaml"
    if not prof.exists():
        sys.exit(f"no profile: {prof}")
    doc = yaml.safe_load(prof.read_text(encoding="utf-8"))
    def render(src, flags):
        return (
            f"# GENERATED by scripts/profile-to-flags.py from deploy/{app}/profile.yaml ({src}) -- DO NOT EDIT BY HAND.\n"
            f"# Regenerate after any profile change; CI gate asserts this matches (scripts/check-hardening-env.sh).\n"
            f"# run.sh sources this and passes $HARDEN_FLAGS to `docker run`.\n"
            f'HARDEN_FLAGS="{" ".join(flags)}"\n'
        ).encode("utf-8")

    # (name, source-label, env-filename, values) — the app plus any co-scheduled infra containers.
    # `values` = the app containers; `infra_values: {<container>: {...}}` = per-infra confinement (#98 multi-container).
    targets = [(app, "values", f"{app}.hardening.env", doc.get("values", {}))]
    for name, iv in (doc.get("infra_values") or {}).items():
        targets.append((name, f"infra_values.{name}", f"{name}.hardening.env", iv))

    for _name, src, fname, values in targets:
        if check and want and fname not in want:
            continue
        body = render(src, flags_from_values(values))
        if check:
            sys.stdout.buffer.write(body)                # bytes: no CRLF translation (LF on every OS)
        else:
            out = REPO / "deploy" / app / fname
            out.write_bytes(body)                        # force LF regardless of platform
            sys.stderr.write(f"wrote {out.relative_to(REPO)}\n")

if __name__ == "__main__":
    main()
