# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: detail.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'detail.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FreeTAKServer.model.protobufModel.contact_pb2 as contact__pb2
import FreeTAKServer.model.protobufModel.group_pb2 as group__pb2
import FreeTAKServer.model.protobufModel.precisionlocation_pb2 as precisionlocation__pb2
import FreeTAKServer.model.protobufModel.status_pb2 as status__pb2
import FreeTAKServer.model.protobufModel.takv_pb2 as takv__pb2
import FreeTAKServer.model.protobufModel.track_pb2 as track__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x64\x65tail.proto\x1a\rcontact.proto\x1a\x0bgroup.proto\x1a\x17precisionlocation.proto\x1a\x0cstatus.proto\x1a\ntakv.proto\x1a\x0btrack.proto\"\xc1\x01\n\x06\x44\x65tail\x12\x11\n\txmlDetail\x18\x01 \x01(\t\x12\x19\n\x07\x63ontact\x18\x02 \x01(\x0b\x32\x08.Contact\x12\x15\n\x05group\x18\x03 \x01(\x0b\x32\x06.Group\x12-\n\x11precisionLocation\x18\x04 \x01(\x0b\x32\x12.PrecisionLocation\x12\x17\n\x06status\x18\x05 \x01(\x0b\x32\x07.Status\x12\x13\n\x04takv\x18\x06 \x01(\x0b\x32\x05.Takv\x12\x15\n\x05track\x18\x07 \x01(\x0b\x32\x06.Trackb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'detail_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DETAIL']._serialized_start=109
  _globals['_DETAIL']._serialized_end=302
# @@protoc_insertion_point(module_scope)
