# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: takmessage.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'takmessage.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import FreeTAKServer.model.protobufModel.cotevent_pb2 as cotevent__pb2
import FreeTAKServer.model.protobufModel.takcontrol_pb2 as takcontrol__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10takmessage.proto\x1a\x0e\x63otevent.proto\x1a\x10takcontrol.proto\"J\n\nTakMessage\x12\x1f\n\ntakControl\x18\x01 \x01(\x0b\x32\x0b.TakControl\x12\x1b\n\x08\x63otEvent\x18\x02 \x01(\x0b\x32\t.CotEventb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'takmessage_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TAKMESSAGE']._serialized_start=54
  _globals['_TAKMESSAGE']._serialized_end=128
# @@protoc_insertion_point(module_scope)
